name: Push Docker image to ECR

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 045678876205.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and tag Docker image
        run: |
          docker build -t short-url-app:latest .
          docker tag short-url-app:latest 045678876205.dkr.ecr.$AWS_REGION.amazonaws.com/short-url-app-repo:latest
        
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 045678876205.dkr.ecr.$AWS_REGION.amazonaws.com/short-url-app-repo:latest